### ISSUE TITLE
Dropdown length is too long

### ISSUE THREAD

**Issue by Sammuel09** [hit-pay/orchid#267]
In this scenario, the dropdown used contains a lot of options, so the list spills to the bottom of the page
It would be nice if we could make the top-center for the modal to be more to the top .
we could also have another prop for center. 

![image](https://github.com/hit-pay/orchid/assets/28958299/92c2f062-aa66-4e02-ba70-d70d670dec52)

**Comment by kewcoder** [comment]
this issue has fixed by @mykhailo-diakovych
